"""ASS (libass) subtitle generation for animated word-level captions.

Every word is its own positioned event, split into up to three states:
  before it is spoken -> active (while spoken, until the next word starts) -> after.
Because positions are computed by our layout engine, highlighting or scaling one word never
reflows the line, which keeps captions perfectly steady.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from shortforge.engines.captions.layout import (
    CapWord,
    LayoutConfig,
    Page,
    TextMeasurer,
    layout_pages,
    libass_em_ratio,
    max_text_width,
)
from shortforge.engines.captions.presets import CaptionPreset


def ass_color(hex_color: str, alpha: float = 0.0) -> str:
    """'#RRGGBB' + alpha(0 opaque..1 transparent) -> '&HAABBGGRR'."""
    h = hex_color.lstrip("#")
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    r, g, b = h[0:2], h[2:4], h[4:6]
    a = max(0, min(255, round(alpha * 255)))
    return f"&H{a:02X}{b}{g}{r}".upper()


def ass_time(t: float) -> str:
    t = max(0.0, t)
    cs = round(t * 100)
    h, rem = divmod(cs, 360000)
    m, rem = divmod(rem, 6000)
    s, cs = divmod(rem, 100)
    return f"{h}:{m:02d}:{s:02d}.{cs:02d}"


def escape_text(text: str) -> str:
    return text.replace("\\", "\\\\").replace("{", "(").replace("}", ")").replace("\n", " ")


def rounded_rect(w: float, h: float, r: float) -> str:
    """ASS vector drawing of a rounded rectangle with its top-left at (0,0)."""
    r = max(0.0, min(r, w / 2, h / 2))
    k = 0.4477 * r  # bezier handle offset for quarter circles
    return (f"m {r:.1f} 0 l {w - r:.1f} 0 b {w - k:.1f} 0 {w:.1f} {k:.1f} {w:.1f} {r:.1f} "
            f"l {w:.1f} {h - r:.1f} b {w:.1f} {h - k:.1f} {w - k:.1f} {h:.1f} {w - r:.1f} {h:.1f} "
            f"l {r:.1f} {h:.1f} b {k:.1f} {h:.1f} 0 {h - k:.1f} 0 {h - r:.1f} "
            f"l 0 {r:.1f} b 0 {k:.1f} {k:.1f} 0 {r:.1f} 0")


@dataclass
class HookOverlay:
    text: str
    start: float = 0.0
    end: float = 2.8


class AssBuilder:
    def __init__(self, preset: CaptionPreset, cfg: LayoutConfig) -> None:
        self.preset = preset
        self.cfg = cfg
        self.events: list[str] = []

    # ------------------------------------------------------------------ header
    def header(self) -> str:
        p = self.preset
        size = p.font_size / libass_em_ratio(str(p.font_path))
        hook_size = 60 / libass_em_ratio(str(p.hook_font_path))
        shadow_alpha = 1 - p.shadow_alpha
        return "\n".join([
            "[Script Info]",
            "; Generated by ShortForge AI",
            "ScriptType: v4.00+",
            f"PlayResX: {self.cfg.width}",
            f"PlayResY: {self.cfg.height}",
            "ScaledBorderAndShadow: yes",
            "WrapStyle: 2",
            "YCbCr Matrix: TV.709",
            "",
            "[V4+ Styles]",
            "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, "
            "Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, "
            "MarginL, MarginR, MarginV, Encoding",
            f"Style: Word,{p.font_name},{size:.2f},{ass_color(p.primary_color)},{ass_color(p.highlight_color)},"
            f"{ass_color(p.outline_color)},{ass_color(p.shadow_color, shadow_alpha)},0,0,0,0,100,100,"
            f"{p.letter_spacing:.1f},0,1,{p.outline_width:.1f},{p.shadow_depth:.1f},5,0,0,0,1",
            f"Style: Box,{p.font_name},{size:.2f},{ass_color(p.box.color, 1 - p.box.alpha)},&H00FFFFFF,"
            f"&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0,0,7,0,0,0,1",
            f"Style: Hook,{p.hook_font_name},{hook_size:.2f},{ass_color(p.hook_text_color)},&H00FFFFFF,"
            f"&H00000000,&H64000000,0,0,0,0,100,100,0,0,1,0,0,5,0,0,0,1",
            "",
            "[Events]",
            "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
        ])

    def _event(self, layer: int, start: float, end: float, style: str, text: str) -> None:
        if end - start < 0.01:
            return
        self.events.append(f"Dialogue: {layer},{ass_time(start)},{ass_time(end)},{style},,0,0,0,,{text}")

    # ------------------------------------------------------------------ captions
    def _entry_tags(self, x: float, y: float, entering: bool, exiting: bool, duration_ms: int) -> str:
        p = self.preset
        tags = ""
        if entering:
            if p.animation == "pop":
                tags += r"\fscx78\fscy78\t(0,110,\fscx100\fscy100)"
            elif p.animation == "bounce":
                tags += r"\fscx70\fscy70\t(0,90,\fscx112\fscy112)\t(90,170,\fscx100\fscy100)"
            elif p.animation == "slide":
                return tags + fr"\move({x:.1f},{y + 28:.1f},{x:.1f},{y:.1f},0,120)" + (
                    r"\fad(90,0)" if not exiting else r"\fad(90,90)")
            elif p.animation == "fade":
                tags += r"\fad(120,0)" if not exiting else r"\fad(120,100)"
        if exiting and p.animation == "fade" and not entering:
            tags += r"\fad(0,100)"
        return tags + fr"\pos({x:.1f},{y:.1f})"

    def add_page(self, page: Page) -> None:
        p = self.preset
        base_scale = page.font_scale
        # Page background box(es), one per line.
        if p.box.enabled:
            for x0, x1, yc in page.lines:
                lh = p.font_size * base_scale * 1.18
                w = (x1 - x0) + 2 * p.box.padding_x
                h = lh + 2 * p.box.padding_y - p.font_size * base_scale * 0.18
                bx, by = x0 - p.box.padding_x, yc - h / 2
                blur = fr"\blur{p.box.blur:.1f}" if p.box.blur else ""
                fade = r"\fad(100,80)" if p.animation in ("fade", "slide") else ""
                self._event(0, page.start, page.end, "Box",
                            fr"{{\an7\pos({bx:.1f},{by:.1f})\bord0\shad0{blur}{fade}\p1}}{rounded_rect(w, h, p.box.radius)}{{\p0}}")
        words = page.words
        for i, w in enumerate(words):
            active_start = w.start
            active_end = words[i + 1].start if i + 1 < len(words) else page.end
            active_end = max(active_end, w.end if i + 1 == len(words) else active_end)
            base_color = p.primary_color
            if p.speaker_colors and w.speaker is not None:
                base_color = p.speaker_colors[w.speaker % len(p.speaker_colors)]
            if w.emphasis:
                base_color = p.emphasis_color
            spoken_color = p.spoken_color or base_color
            if w.emphasis:
                spoken_color = p.emphasis_color
            fs = fr"\fs{p.font_size * base_scale / libass_em_ratio(str(p.font_path)):.2f}" if base_scale != 1.0 else ""
            emph_scale = p.emphasis_scale if w.emphasis else 1.0
            scale_tag = fr"\fscx{emph_scale * 100:.0f}\fscy{emph_scale * 100:.0f}" if emph_scale != 1.0 else ""
            blur = fr"\blur{p.blur:.1f}" if p.blur else ""

            segments: list[tuple[float, float, str]] = []
            if active_start > page.start:
                pre_color = p.primary_color if p.highlight_mode == "karaoke" else base_color
                segments.append((page.start, active_start, "pre:" + pre_color))
            segments.append((active_start, active_end, "active"))
            if active_end < page.end:
                segments.append((active_end, page.end, "post:" + spoken_color))

            for s0, s1, kind in segments:
                entering = abs(s0 - page.start) < 1e-6
                exiting = abs(s1 - page.end) < 1e-6
                tags = self._entry_tags(w.x, w.y, entering, exiting, int((s1 - s0) * 1000))
                if kind == "active":
                    if p.highlight_mode == "none":
                        color = base_color
                        anim = ""
                    elif p.highlight_mode == "box":
                        color = p.highlight_color
                        anim = ""
                        m = TextMeasurer(p.font_path, p.font_size * base_scale)
                        bw = w.width + 26
                        bh = m.line_height() * 0.98
                        self._event(1, s0, s1, "Box",
                                    fr"{{\an7\pos({w.x - bw / 2:.1f},{w.y - bh / 2:.1f})\1c{ass_color(p.highlight_box_color)}"
                                    fr"\1a&H00&\bord0\shad0\fscx92\fscy92\t(0,70,\fscx100\fscy100)\p1}}"
                                    fr"{rounded_rect(bw, bh, 14)}{{\p0}}")
                    else:
                        color = p.highlight_color
                        sc = p.active_scale * emph_scale * 100
                        anim = fr"\t(0,70,\fscx{sc:.0f}\fscy{sc:.0f})" if p.active_scale != 1.0 else ""
                    text = fr"{{{tags}{fs}{scale_tag}{blur}\1c{ass_color(color)}{anim}}}{escape_text(w.text)}"
                else:
                    color = kind.split(":", 1)[1]
                    text = fr"{{{tags}{fs}{scale_tag}{blur}\1c{ass_color(color)}}}{escape_text(w.text)}"
                self._event(2, s0, s1, "Word", text)

    # ------------------------------------------------------------------ hook overlay
    def add_hook(self, hook: HookOverlay) -> None:
        p = self.preset
        m = TextMeasurer(p.hook_font_path, 60)
        max_w = max_text_width(self.cfg) * 0.92
        words = hook.text.split()
        lines: list[str] = []
        cur = ""
        for word in words:
            trial = f"{cur} {word}".strip()
            if m.width(trial) <= max_w - 48 or not cur:
                cur = trial
            else:
                lines.append(cur)
                cur = word
        if cur:
            lines.append(cur)
        lines = lines[:2]
        lh = 60 * 1.25
        top = self.cfg.safe.top * self.cfg.height + 90
        for li, line in enumerate(lines):
            w = m.width(line) + 48
            h = lh + 10
            cx = self.cfg.width / 2
            cy = top + li * (h + 8)
            self._event(3, hook.start, hook.end, "Box",
                        fr"{{\an7\pos({cx - w / 2:.1f},{cy - h / 2:.1f})\1c{ass_color(p.hook_box_color)}\1a&H00&"
                        fr"\bord0\shad2\4a&HB0&\fad(150,150)\fscx85\fscy85\t(0,140,\fscx100\fscy100)\p1}}"
                        fr"{rounded_rect(w, h, 16)}{{\p0}}")
            self._event(4, hook.start, hook.end, "Hook",
                        fr"{{\pos({cx:.1f},{cy:.1f})\fad(150,150)\fscx85\fscy85\t(0,140,\fscx100\fscy100)}}"
                        f"{escape_text(line)}")

    def build(self) -> str:
        return self.header() + "\n" + "\n".join(self.events) + "\n"


def build_ass(words: list[CapWord], preset: CaptionPreset, cfg: LayoutConfig, *, clip_duration: float,
              hook: HookOverlay | None = None, max_words: int | None = None,
              vertical_position: float | None = None) -> tuple[str, list[Page]]:
    pages = layout_pages(words, preset, cfg, clip_duration, max_words, vertical_position)
    builder = AssBuilder(preset, cfg)
    for page in pages:
        builder.add_page(page)
    if hook and hook.text:
        builder.add_hook(hook)
    return builder.build(), pages


def write_ass(path: Path, content: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path
