"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-27 14:58:53.099808
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import shortforge.database.models

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caption_styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_at', shortforge.database.models.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('channels',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('handle', sa.String(length=120), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('banner_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', shortforge.database.models.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resource', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('short_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=False),
    sa.Column('not_before', shortforge.database.models.UTCDateTime(), nullable=True),
    sa.Column('created_at', shortforge.database.models.UTCDateTime(), nullable=False),
    sa.Column('started_at', shortforge.database.models.UTCDateTime(), nullable=True),
    sa.Column('finished_at', shortforge.database.models.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_short_id'), ['short_id'], unique=False)
        batch_op.create_index('ix_jobs_status_priority', ['status', 'priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_video_id'), ['video_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('created_at', shortforge.database.models.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', shortforge.database.models.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=True),
    sa.Column('playlist_id', sa.String(length=64), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_scan', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('scan_interval_min', sa.Integer(), nullable=True),
    sa.Column('max_videos_per_scan', sa.Integer(), nullable=False),
    sa.Column('min_duration_s', sa.Float(), nullable=True),
    sa.Column('max_duration_s', sa.Float(), nullable=True),
    sa.Column('max_video_age_days', sa.Integer(), nullable=True),
    sa.Column('max_shorts_per_video', sa.Integer(), nullable=True),
    sa.Column('max_shorts_per_day', sa.Integer(), nullable=True),
    sa.Column('min_candidate_score', sa.Float(), nullable=True),
    sa.Column('short_min_s', sa.Float(), nullable=True),
    sa.Column('short_max_s', sa.Float(), nullable=True),
    sa.Column('preferred_style', sa.String(length=60), nullable=True),
    sa.Column('reframe_mode', sa.String(length=30), nullable=True),
    sa.Column('upload_destination', sa.String(length=120), nullable=True),
    sa.Column('schedule_strategy', sa.String(length=30), nullable=True),
    sa.Column('auto_download', sa.Boolean(), nullable=False),
    sa.Column('process_existing', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_scan_at', shortforge.database.models.UTCDateTime(), nullable=True),
    sa.Column('next_scan_at', shortforge.database.models.UTCDateTime(), nullable=True),
    sa.Column('created_at', shortforge.database.models.UTCDateTime(), nullable=False),
    sa.Column('updated_at', shortforge.database.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_id', sa.String(length=32), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.String(length=64), nullable=True),
    sa.Column('channel_name', sa.String(length=300), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_path', sa.Text(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('published_at', shortforge.database.models.UTCDateTime(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('proxy_path', sa.Text(), nullable=True),
    sa.Column('audio_path', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('download_status', sa.String(length=20), nullable=False),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('transcript_status', sa.String(length=20), nullable=False),
    sa.Column('scenes_status', sa.String(length=20), nullable=False),
    sa.Column('analysis_status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('discovered_at', shortforge.database.models.UTCDateTime(), nullable=False),
    sa.Column('updated_at', shortforge.database.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('youtube_id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_source_id'), ['source_id'], unique=False)
        batch_op.create_index('ix_videos_source_status', ['source_id', 'processing_status'], unique=False)

    op.create_table('candidate_clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('first_word_idx', sa.Integer(), nullable=True),
    sa.Column('last_word_idx', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('hook_text', sa.String(length=300), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('heuristic_score', sa.Float(), nullable=False),
    sa.Column('llm_score', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of', sa.Integer(), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('pass_reached', sa.Integer(), nullable=False),
    sa.Column('llm_model', sa.String(length=80), nullable=True),
    sa.Column('created_at', shortforge.database.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_clips', schema=None) as batch_op:
        batch_op.create_index('ix_candidates_video_score', ['video_id', 'score'], unique=False)

    op.create_table('downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('quality', sa.String(length=20), nullable=False),
    sa.Column('format_id', sa.String(length=80), nullable=True),
    sa.Column('bytes_total', sa.Integer(), nullable=True),
    sa.Column('bytes_done', sa.Integer(), nullable=True),
    sa.Column('speed_bps', sa.Float(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', shortforge.database.models.UTCDateTime(), nullable=True),
    sa.Column('finished_at', shortforge.database.models.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_downloads_video_id'), ['video_id'], unique=False)

    op.create_table('faces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('w', sa.Float(), nullable=False),
    sa.Column('h', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('mouth_activity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faces', schema=None) as batch_op:
        batch_op.create_index('ix_faces_video_t', ['video_id', 't'], unique=False)

    op.create_table('objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('w', sa.Float(), nullable=False),
    sa.Column('h', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.create_index('ix_objects_video_t', ['video_id', 't'], unique=False)

    op.create_table('scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenes_video_id'), ['video_id'], unique=False)

    op.create_table('speakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('speaking_time', sa.Float(), nullable=True),
    sa.Column('avg_x', sa.Float(), nullable=True),
    sa.Column('avg_y', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('speakers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_speakers_video_id'), ['video_id'], unique=False)

    op.create_table('timeline_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('interest', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_segments_video_id'), ['video_id'], unique=False)

    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('device', sa.String(length=20), nullable=True),
    sa.Column('compute_type', sa.String(length=30), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('language_probability', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('segments', sa.JSON(), nullable=False),
    sa.Column('sentences', sa.JSON(), nullable=False),
    sa.Column('elapsed_s', sa.Float(), nullable=True),
    sa.Column('created_at', shortforge.database.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcripts_video_id'), ['video_id'], unique=False)

    op.create_table('video_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('codec', sa.String(length=40), nullable=True),
    sa.Column('created_at', shortforge.database.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_files_video_id'), ['video_id'], unique=False)

    op.create_table('clip_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_clips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clip_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clip_scores_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('shorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('metadata_options', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('caption_preset', sa.String(length=60), nullable=True),
    sa.Column('reframe_mode', sa.String(length=30), nullable=True),
    sa.Column('render_profile', sa.String(length=20), nullable=True),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('output_path', sa.Text(), nullable=True),
    sa.Column('thumbnail_path', sa.Text(), nullable=True),
    sa.Column('cover_path', sa.Text(), nullable=True),
    sa.Column('qc_status', sa.String(length=10), nullable=True),
    sa.Column('qc_report', sa.JSON(), nullable=True),
    sa.Column('repair_attempts', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.JSON(), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', shortforge.database.models.UTCDateTime(), nullable=False),
    sa.Column('updated_at', shortforge.database.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_clips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shorts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shorts_video_id'), ['video_id'], unique=False)

    op.create_table('transcript_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=200), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('segment_idx', sa.Integer(), nullable=False),
    sa.Column('sentence_idx', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcript_words', schema=None) as batch_op:
        batch_op.create_index('ix_words_transcript_idx', ['transcript_id', 'idx'], unique=False)

    op.create_table('analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_id', sa.Integer(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', shortforge.database.models.UTCDateTime(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('average_view_duration', sa.Float(), nullable=True),
    sa.Column('average_view_percentage', sa.Float(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['short_id'], ['shorts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.create_index('ix_analytics_short_fetched', ['short_id', 'fetched_at'], unique=False)

    op.create_table('edit_timelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('created_at', shortforge.database.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['short_id'], ['shorts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edit_timelines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edit_timelines_short_id'), ['short_id'], unique=False)

    op.create_table('learning_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_id', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('performance', sa.Float(), nullable=True),
    sa.Column('updated_at', shortforge.database.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['short_id'], ['shorts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_id')
    )
    op.create_table('renders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_id', sa.Integer(), nullable=False),
    sa.Column('timeline_version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('profile', sa.String(length=20), nullable=True),
    sa.Column('encoder', sa.String(length=40), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('elapsed_s', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', shortforge.database.models.UTCDateTime(), nullable=True),
    sa.Column('finished_at', shortforge.database.models.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['short_id'], ['shorts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('renders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_renders_short_id'), ['short_id'], unique=False)

    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=120), nullable=True),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', shortforge.database.models.UTCDateTime(), nullable=True),
    sa.Column('publish_at', shortforge.database.models.UTCDateTime(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('made_for_kids', sa.Boolean(), nullable=False),
    sa.Column('playlist_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('bytes_sent', sa.Integer(), nullable=True),
    sa.Column('speed_bps', sa.Float(), nullable=True),
    sa.Column('processing_status', sa.String(length=40), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', shortforge.database.models.UTCDateTime(), nullable=True),
    sa.Column('finished_at', shortforge.database.models.UTCDateTime(), nullable=True),
    sa.Column('created_at', shortforge.database.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['short_id'], ['shorts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploads_short_id'), ['short_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploads_youtube_video_id'), ['youtube_video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploads_youtube_video_id'))
        batch_op.drop_index(batch_op.f('ix_uploads_short_id'))

    op.drop_table('uploads')
    with op.batch_alter_table('renders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_renders_short_id'))

    op.drop_table('renders')
    op.drop_table('learning_features')
    with op.batch_alter_table('edit_timelines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edit_timelines_short_id'))

    op.drop_table('edit_timelines')
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.drop_index('ix_analytics_short_fetched')

    op.drop_table('analytics')
    with op.batch_alter_table('transcript_words', schema=None) as batch_op:
        batch_op.drop_index('ix_words_transcript_idx')

    op.drop_table('transcript_words')
    with op.batch_alter_table('shorts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shorts_video_id'))

    op.drop_table('shorts')
    with op.batch_alter_table('clip_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clip_scores_candidate_id'))

    op.drop_table('clip_scores')
    with op.batch_alter_table('video_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_files_video_id'))

    op.drop_table('video_files')
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcripts_video_id'))

    op.drop_table('transcripts')
    with op.batch_alter_table('timeline_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeline_segments_video_id'))

    op.drop_table('timeline_segments')
    with op.batch_alter_table('speakers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_speakers_video_id'))

    op.drop_table('speakers')
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenes_video_id'))

    op.drop_table('scenes')
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.drop_index('ix_objects_video_t')

    op.drop_table('objects')
    with op.batch_alter_table('faces', schema=None) as batch_op:
        batch_op.drop_index('ix_faces_video_t')

    op.drop_table('faces')
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_downloads_video_id'))

    op.drop_table('downloads')
    with op.batch_alter_table('candidate_clips', schema=None) as batch_op:
        batch_op.drop_index('ix_candidates_video_score')

    op.drop_table('candidate_clips')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index('ix_videos_source_status')
        batch_op.drop_index(batch_op.f('ix_videos_source_id'))
        batch_op.drop_index(batch_op.f('ix_videos_content_hash'))

    op.drop_table('videos')
    op.drop_table('sources')
    op.drop_table('settings')
    op.drop_table('notifications')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_video_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_type'))
        batch_op.drop_index('ix_jobs_status_priority')
        batch_op.drop_index(batch_op.f('ix_jobs_short_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_dedupe_key'))

    op.drop_table('jobs')
    op.drop_table('channels')
    op.drop_table('caption_styles')
    # ### end Alembic commands ###
